/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import Dexie from "dexie";

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import {
  CacheFirst,
  NetworkFirst,
  StaleWhileRevalidate,
} from "workbox-strategies";
import { CacheOnly } from "workbox-strategies";
import { Strategy } from "workbox-strategies";

import { CacheableResponsePlugin } from "workbox-cacheable-response";
import { setCatchHandler } from "workbox-routing";
import { getData, getData2 } from "./get";
import db from "./db";

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // console.log(request, url);
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith("/_")) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => {
    return url.origin === self.location.origin && url.pathname.endsWith(".png"); // Customize this strategy as needed, e.g., by changing to CacheFirst.
  },
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

class Idb extends Strategy {
  _handle(request, handler) {
    const fetchAndCachePutDone = handler.fetchAndCachePut(request);
    const cacheMatchDone = handler.cacheMatch(request);

    // // Now add some values.
    // db.open()
    //   .then(function () {
    //     return db.friends.add({ name: "Foo", age: 42 });
    //   })
    //   .then(function () {
    //     return db.friends.where("age").between(40, 65).toArray();
    //   })
    //   .then(function (friends) {
    //     console.log("Found friends: " + JSON.stringify(friends, null, 2));
    //   })
    //   .catch(Dexie.MissingAPIError, function (e) {
    //     console.log("Couldn't find indexedDB API");
    //   })
    //   .catch("SecurityError", function (e) {
    //     console.log(
    //       "SeurityError - This browser doesn't like fiddling with indexedDB."
    //     );
    //     console.log(
    //       "If using Safari, this is because jsfiddle runs its samples within an iframe"
    //     );
    //     console.log(
    //       "Go run some samples instead at: https://github.com/dfahlander/Dexie.js/wiki/Samples"
    //     );
    //   })
    //   .catch(function (e) {
    //     console.log(e);
    //   });

    return new Promise((resolve, reject) => {
      fetchAndCachePutDone.then(resolve);
      cacheMatchDone.then((response) => response && resolve(response));

      // Reject if both network and cache error or find no response.
      Promise.allSettled([fetchAndCachePutDone, cacheMatchDone]).then(
        (results) => {
          const [fetchAndCachePutResult, cacheMatchResult] = results;
          if (
            fetchAndCachePutResult.status === "rejected" &&
            !cacheMatchResult.value
          ) {
            reject(fetchAndCachePutResult.reason);
          }
        }
      );
    });
  }
}

class IndexedDbStrategy extends Strategy {
  _handle(request, handler) {
    return new Promise(async (resolve, reject) => {
      try {
        /**
         * If we are offline, fetch from indexedDb
         */
        if (!navigator.onLine) {
          await db.open();
          const cachedData = await db.addresses
            .where("url")
            .equals(request.url)
            .first();
          resolve(
            new Response(JSON.stringify(cachedData.data), {
              headers: { "Content-Type": "text/json" },
              status: 200,
              statusText: "I am a custom service worker response!",
            })
          );
          return;
        }
        /**
         * If we are online, fetch from remote and cache response
         * in indexedDb
         */
        const response = await handler.fetch(request);
        const clonedResponse = response.clone();
        const data = await clonedResponse.json();

        // Now add some values.
        try {
          await db.open();
          await db.addresses.put({ url: request.url, data });
        } catch (e) {
          console.error(e);
        }

        resolve(response);
      } catch (er) {
        console.error(er);
        reject(er);
      }
    });
  }
}

// self.addEventListener('fetch', function(event) {                         1
//   if (/\.jpg$/.test(event.request.url)) {                                2
//     event.respondWith(
//     new Response('<p>This is a response that comes from your service worker!</p>', {
//        headers: { 'Content-Type': 'text/html' }                          3
//       });
//     );
//   }
// });

registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => {
    return url.pathname === "/api/address/random_address";
  },
  //https://developer.chrome.com/docs/workbox/modules/workbox-strategies/#network-first-network-falling-back-to-cache
  new IndexedDbStrategy()
);

// // This allows the web app to trigger skipWaiting via
// // registration.waiting.postMessage({type: 'SKIP_WAITING'})
// self.addEventListener('message', (event) => {
//   if (event.data && event.data.type === 'SKIP_WAITING') {
//     self.skipWaiting();
//   }
// });

// // Any other custom service worker logic can go here.

// service-worker.js
// On the Service Worker side we have to listen to the message event
self.addEventListener("message", async (event) => {
  if (event.data && event.data.type === "MESSAGE_IDENTIFIER") {
    // do something
    console.log(event);
    const data = await getData();
    console.log(data);
  }
});
